### ISSUE TITLE
Block comments are not formatted correctly

### ISSUE THREAD

**Issue by doctr-oof** [LuaLS/lua.tmbundle#20]
## Summary
GitHub Linguist [recently started using this grammar](https://github.com/github-linguist/linguist/pull/6661) in its latest release. Since then, it has come to my attention that block comments simply do not work as expected when viewing Lua files on GitHub. This makes it extremely difficult to review PRs that contain block comments. This is reproduceable by all members on my engineering team.

I am not familiar with creating or editing grammar files, so I cannot fix this myself with a pull request.

## Specifics
- Block comments - regardless of how they are formatted or terminated - are not actually interpreted as comments. (See **Example 1** below)
- Block comments terminated with a leading double-dash (`--]]`) cause all file contents below it to be interpreted as plaintext. (See **Example 2** below)
- This issue appears to occur 100% of the time regardless of the file's remaining text content.

## Example(s)
Example 1:
![image](https://github.com/LuaLS/lua.tmbundle/assets/40879886/cb5fbd66-cbfe-45b7-8318-4b3271522e82)

Example 2:
![image](https://github.com/LuaLS/lua.tmbundle/assets/40879886/26106a5e-7507-4014-a871-a639360fc6e1)

**Comment by lewri** [comment]
It looks like block comments following this change can deal with `]]--` instead of `--]]`.
Edit: For clarification I'm not saying one is more right over the other (Lua is designed to accept both) but the bottom line should be that both are handled correctly.

Examples:
with `--]]`
![image](https://github.com/LuaLS/lua.tmbundle/assets/20030128/da111432-6c8d-4649-939d-b453ad2652a8)

with `]]--`
![image](https://github.com/LuaLS/lua.tmbundle/assets/20030128/692dc7d5-bb18-4435-af79-d315b428cacc)

**Comment by sumneko** [comment]
Many thanks!
